name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  lint-and-tests:
    name: Linting and Tests
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "False"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Linting
        run: |
          flake8 .

      - name: Run tests for oc_lettings_site
        run: |
          pytest oc_lettings_site/tests \
          --cov=oc_lettings_site \
          --cov-fail-under=80

      - name: Run tests for lettings
        run: |
          pytest lettings/tests \
          --cov=lettings \
          --cov-fail-under=80

      - name: Run tests for profiles
        run: |
          pytest profiles/tests \
          --cov=profiles \
          --cov-fail-under=80

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: lint-and-tests

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:latest

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: docker

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Generate Dockerun.aws.json
        run: |
          cat > Dockerrun.aws.json <<EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:${{
          github.sha }}",
              "Update': "true",
            },
            "Ports": [
              {
                "ContainerPort": 8000
              }
            ]
          }
          EOF

      - name: Create deployment package
        run: |
          zip deploy-${{ github.sha }}-${{ github.run_number }}.zip \
          Dockerrun.aws.json

      - name: Upload deployment package to S3
        run: |
          aws s3 cp deploy-${{ github.sha }}-${{ github.run_number }}.zip s3://${{ secrets.EB_S3_BUCKET }}/deploy-${{ github.sha }}-${{ github.run_number }}.zip

      - name: Create Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --region eu-west-3 \
            --application-name "${{ secrets.EB_APPLICATION_NAME }}" \
            --version-label "${{ github.sha }}-${{ github.run_number }}" \
            --source-bundle S3Bucket="${{ steps.eb_bucket.outputs.bucket }}",S3Key="deploy-${{ github.sha }}-${{ github.run_number }}.zip"


      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --region eu-west-3 \
            --environment-name "${{ secrets.EB_ENVIRONMENT_NAME }}" \
            --version-label "${{ github.sha }}-${{ github.run_number }}"
